version: "3.9"

services:
  app:
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - SAMPLE_ENV=sample_env
    volumes:
      - ./coverage:/project/coverage
